### PR TITLE
Update shape.js

### PR DESCRIPTION
**Pull request by dbleier**
changed `function isEven(num)` to `isEven = function(num)` for older browser support

### CODE REVIEW

**Comment by justinbmeyer** [comment]
Thanks.  There's a browser that doesn't support named functions?

**Comment by phillipskevin** [comment]
@dbleier I think the saucelabs tests are failing because your fork doesn't have access to the environment variables used to connect to saucelabs. I'll figure out if there's some way around this tomorrow, but for now I've put in a separate PR: #140.

**Comment by dbleier** [comment]
@phillipskevin thanks

**Comment by phillipskevin** [comment]
I released that fix in `can-reflect@1.17.3`.

**Comment by justinbmeyer** [comment]
@phillipskevin would we have seen this if we also put strict mode in the file?  Perhaps we should have to "test" that the code is working in strict mode?

**Comment by dbleier** [comment]
@phillipskevin thanks
@justinbmeyer I thought canjs always was supposed to run in strict mode?

**Comment by phillipskevin** [comment]
`"use strict";` is in the file. I'm not sure why this error is only thrown by a specific browser.

We would have caught this if jshint was running correctly. I opened https://github.com/canjs/can-reflect/issues/139 to fix this.

**Pull request closed without merging**
